#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SVBClient.Resource", IsApplication=true)]

namespace SVBClient
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle_orange_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int circle_red_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int circle_yellow_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gps = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hand = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int stop = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int SVBLogo64 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tool = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tool2 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int CarPhoneEdit = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int ConfigBtn = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int PasswordEdit = 2131034131;
			
			// aapt resource value: 0x7f050010
			public const int Qib = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int StopBtn = 2131034126;
			
			// aapt resource value: 0x7f050011
			public const int SvbBrowser = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int WhereBtn = 2131034125;
			
			// aapt resource value: 0x7f050004
			public const int editText1 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout0 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout2 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int linearLayout4 = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int mob1 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int mob2 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int numvehicle = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int passwd = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int relativeLayout1 = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int sendconfigbtn = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CompassLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConfigActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MapViewActivity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int StopActivity = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int ApplicationName = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int Command = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int Config = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int ConfigSvb = 2130968576;
			
			// aapt resource value: 0x7f040009
			public const int Password = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int PasswordV = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int Phone1 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int Phone2 = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int PhoneCar = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int SVBWelcome = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int Send = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int StopTitle = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
